#!/usr/bin/env python3
"""
build-falsification-tracker.py — track counter-hypothesis testing status.

For each atom in wiki/claims/, extracts:
  - fr.verdict (CORROBORATED / NEEDS_MORE_EVIDENCE / WEAKENED / UNFALSIFIABLE)
  - ## Falsification condition text
  - Whether the falsification was actually TESTED

Heuristic for TESTED status:
  - CORROBORATED + STRONG → TESTED (survived falsification attempt)
  - CORROBORATED + MODERATE → PARTIAL (corroborated but counter-hypothesis not fully excluded)
  - NEEDS_MORE_EVIDENCE → UNTESTED
  - WEAKENED → TESTED (falsified)
  - UNFALSIFIABLE → UNFALSIFIABLE
  - Has "## Spot-check" section with content → adds evidence of testing

Outputs:
    wiki/_falsification-tracker.md — summary + per-atom status
    output/falsification-tracker.json — machine-readable

Usage:
    python3 scripts/build-falsification-tracker.py
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CLAIMS_DIR = REPO_ROOT / "wiki" / "claims"
OUTPUT_MD = REPO_ROOT / "wiki" / "_falsification-tracker.md"
OUTPUT_JSON = REPO_ROOT / "output" / "falsification-tracker.json"

PAT_VERDICT = re.compile(r'fr\.verdict\s*=\s*"([^"]+)"')
PAT_STRENGTH = re.compile(r'fr\.strength\s*=\s*"([^"]+)"')
PAT_RESULT_ID = re.compile(r'resultId:\s*"([^"]+)"')
PAT_LAYER = re.compile(r"^\*\*Layer:\*\*\s*\[\[../layers/layer-(\d)")
PAT_CLAIM_TYPE = re.compile(r'fr\.claimType\s*=\s*"([^"]+)"')
PAT_FALSIFICATION_SECTION = re.compile(
    r"## Falsification condition\s*\n(.*?)(?=\n## |\Z)", re.DOTALL
)
PAT_COUNTER_HYPOTHESIS = re.compile(
    r"## Counter-hypothesis\s*\n(.*?)(?=\n## |\Z)", re.DOTALL
)
PAT_SPOT_CHECK = re.compile(
    r"## Spot-check.*?\n(.*?)(?=\n## |\Z)", re.DOTALL
)


def determine_test_status(verdict: str, strength: str, has_spot_check: bool, falsification_text: str) -> str:
    """Determine falsification test status from atom metadata."""
    if verdict == "NEEDS_MORE_EVIDENCE":
        return "UNTESTED"
    if verdict == "UNFALSIFIABLE":
        return "UNFALSIFIABLE"
    if verdict == "WEAKENED":
        return "FALSIFIED"
    if verdict == "CORROBORATED":
        if strength == "STRONG":
            return "TESTED"
        if strength == "MODERATE":
            if has_spot_check:
                return "TESTED"
            return "PARTIAL"
    return "UNKNOWN"


def main() -> int:
    if not CLAIMS_DIR.exists():
        print(f"[error] claims dir not found: {CLAIMS_DIR}", file=sys.stderr)
        return 1

    atoms = []
    status_counts = defaultdict(int)
    layer_status = defaultdict(lambda: defaultdict(int))

    for path in sorted(CLAIMS_DIR.glob("*.md")):
        if path.name.startswith("_"):
            continue
        try:
            body = path.read_text(encoding="utf-8")
        except Exception:
            continue

        v_m = PAT_VERDICT.search(body)
        verdict = v_m.group(1) if v_m else "unknown"

        s_m = PAT_STRENGTH.search(body)
        strength = s_m.group(1) if s_m else "unknown"

        rid_m = PAT_RESULT_ID.search(body)
        result_id = rid_m.group(1) if rid_m else ""

        layer_m = None
        for line in body.split("\n")[:10]:
            layer_m = PAT_LAYER.match(line)
            if layer_m:
                break
        layer = int(layer_m.group(1)) if layer_m else 0

        ct_m = PAT_CLAIM_TYPE.search(body)
        claim_type = ct_m.group(1) if ct_m else ""

        fals_m = PAT_FALSIFICATION_SECTION.search(body)
        falsification_text = fals_m.group(1).strip() if fals_m else ""

        counter_m = PAT_COUNTER_HYPOTHESIS.search(body)
        counter_text = counter_m.group(1).strip() if counter_m else ""

        spot_m = PAT_SPOT_CHECK.search(body)
        has_spot_check = spot_m is not None and len(spot_m.group(1).strip()) > 10

        has_counter = len(counter_text) > 10
        has_falsification = len(falsification_text) > 10

        test_status = determine_test_status(verdict, strength, has_spot_check, falsification_text)
        status_counts[test_status] += 1
        layer_status[layer][test_status] += 1

        atoms.append({
            "file": path.name,
            "result_id": result_id,
            "layer": layer,
            "claim_type": claim_type,
            "verdict": verdict,
            "strength": strength,
            "test_status": test_status,
            "has_counter_hypothesis": has_counter,
            "has_falsification_condition": has_falsification,
            "has_spot_check": has_spot_check,
        })

    total = len(atoms)

    # Render markdown
    lines = []
    lines.append("# Falsification Tracker")
    lines.append("")
    lines.append("Auto-generated by `scripts/build-falsification-tracker.py`. **Do not edit by hand.**")
    lines.append("")
    lines.append(f"**Total atoms:** {total}")
    lines.append("")

    # Summary
    lines.append("## Falsification Test Status Summary")
    lines.append("")
    lines.append("| Status | Count | % | Meaning |")
    lines.append("|---|---|---|---|")
    status_desc = {
        "TESTED": "Counter-hypothesis tested, claim survived (CORROBORATED/STRONG or MODERATE+spot-check)",
        "PARTIAL": "Corroborated but counter-hypothesis not fully excluded (MODERATE, no spot-check)",
        "UNTESTED": "Falsification condition not yet investigated (NEEDS_MORE_EVIDENCE)",
        "FALSIFIED": "Counter-hypothesis confirmed, claim weakened (WEAKENED)",
        "UNFALSIFIABLE": "Claim cannot be tested by design",
        "UNKNOWN": "Status could not be determined",
    }
    for status in ["TESTED", "PARTIAL", "UNTESTED", "FALSIFIED", "UNFALSIFIABLE", "UNKNOWN"]:
        count = status_counts.get(status, 0)
        pct = f"{count/total*100:.1f}" if total else "0"
        desc = status_desc.get(status, "")
        lines.append(f"| **{status}** | {count} | {pct}% | {desc} |")
    lines.append("")

    # Popper completeness metric
    tested = status_counts.get("TESTED", 0) + status_counts.get("FALSIFIED", 0)
    popper_pct = tested / total * 100 if total else 0
    lines.append(f"**Popper completeness:** {tested}/{total} ({popper_pct:.1f}%) — atoms where falsification was genuinely attempted")
    lines.append("")

    # Layer breakdown
    lines.append("## By Layer")
    lines.append("")
    lines.append("| Layer | TESTED | PARTIAL | UNTESTED | Total | Popper % |")
    lines.append("|---|---|---|---|---|---|")
    for layer in range(1, 8):
        t = layer_status[layer].get("TESTED", 0)
        p = layer_status[layer].get("PARTIAL", 0)
        u = layer_status[layer].get("UNTESTED", 0)
        tot = sum(layer_status[layer].values())
        ppct = f"{t/tot*100:.0f}" if tot else "0"
        lines.append(f"| L{layer} | {t} | {p} | {u} | {tot} | {ppct}% |")
    lines.append("")

    # Contract completeness
    lines.append("## Atom Contract Completeness")
    lines.append("")
    has_counter = sum(1 for a in atoms if a["has_counter_hypothesis"])
    has_fals = sum(1 for a in atoms if a["has_falsification_condition"])
    has_spot = sum(1 for a in atoms if a["has_spot_check"])
    lines.append(f"- **Counter-hypothesis present:** {has_counter}/{total} ({has_counter/total*100:.1f}%)")
    lines.append(f"- **Falsification condition present:** {has_fals}/{total} ({has_fals/total*100:.1f}%)")
    lines.append(f"- **Spot-check performed:** {has_spot}/{total} ({has_spot/total*100:.1f}%)")
    lines.append("")

    # UNTESTED atoms list
    untested = [a for a in atoms if a["test_status"] == "UNTESTED"]
    if untested:
        lines.append("## UNTESTED Atoms (action required)")
        lines.append("")
        lines.append("| File | Layer | claimType | Verdict |")
        lines.append("|---|---|---|---|")
        for a in untested:
            lines.append(f"| `{a['file']}` | L{a['layer']} | {a['claim_type']} | {a['verdict']} |")
        lines.append("")

    # PARTIAL atoms list
    partial = [a for a in atoms if a["test_status"] == "PARTIAL"]
    if partial:
        lines.append("## PARTIAL Atoms (spot-check recommended)")
        lines.append("")
        lines.append("| File | Layer | claimType |")
        lines.append("|---|---|---|")
        for a in partial:
            lines.append(f"| `{a['file']}` | L{a['layer']} | {a['claim_type']} |")
        lines.append("")

    OUTPUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUTPUT_MD}")

    # JSON output
    json_data = {
        "generated": "scripts/build-falsification-tracker.py",
        "total_atoms": total,
        "status_counts": dict(status_counts),
        "popper_completeness_pct": round(popper_pct, 1),
        "contract": {
            "has_counter_hypothesis": has_counter,
            "has_falsification_condition": has_fals,
            "has_spot_check": has_spot,
        },
        "atoms": atoms,
    }
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(json_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUTPUT_JSON}")
    print(f"     total={total}, TESTED={status_counts.get('TESTED',0)}, PARTIAL={status_counts.get('PARTIAL',0)}, UNTESTED={status_counts.get('UNTESTED',0)}, popper={popper_pct:.1f}%")

    return 0


if __name__ == "__main__":
    sys.exit(main())
