#!/usr/bin/env python3
"""
build-coverage-matrix.py — generate Layer × claimType coverage matrix.

Scans wiki/claims/*.md, extracts primary Layer and fr.claimType, and produces
a 7×16 matrix showing atom counts per cell. Empty cells = structural gaps.

Outputs:
    wiki/_coverage-matrix.md  — human-readable matrix + gap analysis
    output/coverage-matrix.json — machine-readable for Aurora/UI consumption

Usage:
    python3 scripts/build-coverage-matrix.py
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CLAIMS_DIR = REPO_ROOT / "wiki" / "claims"
OUTPUT_MD = REPO_ROOT / "wiki" / "_coverage-matrix.md"
OUTPUT_JSON = REPO_ROOT / "output" / "coverage-matrix.json"

STANDARD_TYPES = [
    "evidence_concealment",
    "document_fabrication",
    "regulatory_manipulation",
    "terminology_manipulation",
    "prosecution_misconduct",
    "witness_manipulation",
    "conspiracy_structure",
    "institutional_obstruction",
    "procedural_violation",
    "human_rights_violation",
    "testimony_evidence",
    "cross_layer_analysis",
    "technical_proof",
    "attorney_misconduct",
    "temporal_manipulation",
    "methodology",
]

STANDARD_LABELS_KR = {
    "evidence_concealment": "증거은폐",
    "document_fabrication": "문서위변조",
    "regulatory_manipulation": "훈령조작",
    "terminology_manipulation": "용어조작",
    "prosecution_misconduct": "검찰비위",
    "witness_manipulation": "증인조작",
    "conspiracy_structure": "공모구조",
    "institutional_obstruction": "제도적방해",
    "procedural_violation": "절차위반",
    "human_rights_violation": "인권침해",
    "testimony_evidence": "증언증거",
    "cross_layer_analysis": "층위간분석",
    "technical_proof": "기술적증거",
    "attorney_misconduct": "변호인비위",
    "temporal_manipulation": "시간적조작",
    "methodology": "방법론",
}

PAT_PRIMARY_LAYER = re.compile(r"^\*\*Layer:\*\*\s*\[\[../layers/layer-(\d)")
PAT_CLAIM_TYPE = re.compile(r'fr\.claimType\s*=\s*"([^"]+)"')
PAT_VERDICT = re.compile(r'fr\.verdict\s*=\s*"([^"]+)"')
PAT_STRENGTH = re.compile(r'fr\.strength\s*=\s*"([^"]+)"')


def main() -> int:
    if not CLAIMS_DIR.exists():
        print(f"[error] claims dir not found: {CLAIMS_DIR}", file=sys.stderr)
        return 1

    # matrix[layer][claimType] = list of (filename, verdict, strength)
    matrix: dict[int, dict[str, list[dict]]] = defaultdict(lambda: defaultdict(list))
    non_standard: list[tuple[str, str]] = []
    total = 0

    for path in sorted(CLAIMS_DIR.glob("*.md")):
        if path.name.startswith("_"):
            continue
        try:
            body = path.read_text(encoding="utf-8")
        except Exception:
            continue
        total += 1

        # Extract primary layer (first mentioned)
        layer_m = PAT_PRIMARY_LAYER.search(body, re.MULTILINE)
        if not layer_m:
            # Try line by line
            for line in body.split("\n")[:10]:
                layer_m = PAT_PRIMARY_LAYER.match(line)
                if layer_m:
                    break
        layer = int(layer_m.group(1)) if layer_m else 0

        # Extract claimType
        ct_m = PAT_CLAIM_TYPE.search(body)
        claim_type = ct_m.group(1) if ct_m else "unknown"

        # Extract verdict and strength
        v_m = PAT_VERDICT.search(body)
        verdict = v_m.group(1) if v_m else "unknown"
        s_m = PAT_STRENGTH.search(body)
        strength = s_m.group(1) if s_m else "unknown"

        if claim_type not in STANDARD_TYPES:
            non_standard.append((path.name, claim_type))

        matrix[layer][claim_type].append({
            "file": path.name,
            "verdict": verdict,
            "strength": strength,
        })

    # Build output
    lines = []
    lines.append("# Layer x claimType Coverage Matrix")
    lines.append("")
    lines.append("Auto-generated by `scripts/build-coverage-matrix.py`. **Do not edit by hand.**")
    lines.append("")
    lines.append(f"**Total atoms:** {total}")
    lines.append("")

    # Matrix table
    header = "| Layer |"
    sep = "|---|"
    for ct in STANDARD_TYPES:
        short = STANDARD_LABELS_KR.get(ct, ct[:6])
        header += f" {short} |"
        sep += "---|"

    header += " **Total** |"
    sep += "---|"

    lines.append(header)
    lines.append(sep)

    layer_totals = defaultdict(int)
    type_totals = defaultdict(int)
    gaps = []

    for layer in range(1, 8):
        row = f"| **L{layer}** |"
        row_total = 0
        for ct in STANDARD_TYPES:
            count = len(matrix[layer][ct])
            row_total += count
            type_totals[ct] += count
            if count == 0:
                row += " - |"
                gaps.append((layer, ct))
            else:
                row += f" **{count}** |"
        layer_totals[layer] = row_total
        row += f" {row_total} |"
        lines.append(row)

    # Totals row
    total_row = "| **Total** |"
    for ct in STANDARD_TYPES:
        total_row += f" {type_totals[ct]} |"
    total_row += f" {total} |"
    lines.append(total_row)
    lines.append("")

    # Gap analysis
    lines.append("## Gap Analysis")
    lines.append("")
    lines.append(f"**Empty cells:** {len(gaps)} / {7 * len(STANDARD_TYPES)} ({len(gaps)/(7*len(STANDARD_TYPES))*100:.1f}%)")
    lines.append("")

    if gaps:
        lines.append("| Layer | Missing claimType | Assessment needed |")
        lines.append("|---|---|---|")
        for layer, ct in gaps:
            kr = STANDARD_LABELS_KR.get(ct, ct)
            lines.append(f"| L{layer} | {ct} ({kr}) | N/A or TODO? |")
        lines.append("")
        lines.append("Mark each gap as `N/A` (not applicable to this layer) or `TODO` (atom extraction needed).")
    else:
        lines.append("No gaps detected — all cells populated.")
    lines.append("")

    # Non-standard types
    if non_standard:
        lines.append("## Non-standard claimType values")
        lines.append("")
        lines.append(f"**Count:** {len(non_standard)} atoms with non-standard claimType (should be normalized)")
        lines.append("")
        for fname, ct in non_standard:
            lines.append(f"- `{fname}`: `{ct}`")
        lines.append("")

    # Verdict breakdown per layer
    lines.append("## Verdict Strength by Layer")
    lines.append("")
    lines.append("| Layer | CORR/STRONG | CORR/MOD | NME | Total |")
    lines.append("|---|---|---|---|---|")
    for layer in range(1, 8):
        strong = sum(1 for ct in matrix[layer] for a in matrix[layer][ct] if a["verdict"] == "CORROBORATED" and a["strength"] == "STRONG")
        moderate = sum(1 for ct in matrix[layer] for a in matrix[layer][ct] if a["verdict"] == "CORROBORATED" and a["strength"] == "MODERATE")
        nme = sum(1 for ct in matrix[layer] for a in matrix[layer][ct] if a["verdict"] == "NEEDS_MORE_EVIDENCE")
        t = strong + moderate + nme
        lines.append(f"| L{layer} | {strong} | {moderate} | {nme} | {t} |")
    lines.append("")

    OUTPUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUTPUT_MD}")

    # JSON output
    json_data = {
        "generated": "scripts/build-coverage-matrix.py",
        "total_atoms": total,
        "matrix": {},
        "gaps": [{"layer": l, "claimType": ct} for l, ct in gaps],
        "non_standard": [{"file": f, "claimType": ct} for f, ct in non_standard],
    }
    for layer in range(1, 8):
        json_data["matrix"][f"L{layer}"] = {}
        for ct in STANDARD_TYPES:
            json_data["matrix"][f"L{layer}"][ct] = len(matrix[layer][ct])

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(json_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUTPUT_JSON}")
    print(f"     atoms={total}, gaps={len(gaps)}/{7*len(STANDARD_TYPES)}, non_standard={len(non_standard)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
