#!/usr/bin/env python3
"""
rank-compile-queue.py — Phase 4.2: filter, classify, and rank uncovered leaf sections.

Reads the JSON output of parse-book-sections.py and produces a prioritized
compile queue with split-hint classification:

    CLEAN       100 < words <= 500, records 1–4  → 1 atom per section (auto-OK)
    MODERATE    words 50–100 or 500–1000          → likely 1 atom, review body
    NEEDS_SPLIT words > 1000 or records > 5       → multiple atoms, manual split

Priority score = record_count × (1 + depth_bonus) × layer_urgency_weight
  - depth_bonus: depth 5 gets +0.5 (sub-leaf = more precise proposition)
  - layer_urgency_weight: based on current coverage gaps (L3=3.0, L5=2.5, L6=2.0,
    L4=1.8, L7=1.5, L1=1.0, L2=1.0)

Output: output/phase-4-2-compile-queue-YYYY-MM-DD.md

Usage:
    python3 scripts/rank-compile-queue.py
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = Path("/tmp") / f"book-section-tree-{date.today().isoformat()}.json"
OUTPUT_PATH = (
    REPO_ROOT / "output" / f"phase-4-2-compile-queue-{date.today().isoformat()}.md"
)

# Layer urgency weights — inversely proportional to current coverage %.
# L3 6.5% → highest urgency, L1 34.8% → lowest.
LAYER_URGENCY = {1: 1.0, 2: 1.0, 3: 3.0, 4: 1.8, 5: 2.5, 6: 2.0, 7: 1.5}


def classify(s: dict) -> str:
    w = s["word_count"]
    r = s["record_count"]
    if w > 1000 or r > 5:
        return "NEEDS_SPLIT"
    if 100 < w <= 500 and 1 <= r <= 4:
        return "CLEAN"
    return "MODERATE"


def priority_score(s: dict) -> float:
    depth_bonus = 0.5 if s["depth"] >= 5 else 0.0
    layer_w = LAYER_URGENCY.get(s["layer"], 1.0)
    return s["record_count"] * (1.0 + depth_bonus) * layer_w


def main() -> int:
    if not JSON_PATH.exists():
        print(f"[err] {JSON_PATH} not found. Run parse-book-sections.py --json first.",
              file=sys.stderr)
        return 1

    sections = json.loads(JSON_PATH.read_text(encoding="utf-8"))

    # Filter: uncovered leaves (depth >= 4, record >= 1, words >= 50, no atom_hits)
    # atom_hits field is not in JSON (it's computed at render time), so we
    # re-check: atom_hits was added to sections by the markdown renderer only.
    # In the JSON, there's no atom_hits key. We'll include all matching sections
    # and note that atom_hits filtering was already done by the parent script's
    # uncovered-leaves table. For safety, include all depth>=4 candidates here
    # and let the user cross-check against the full table.
    candidates = [
        s for s in sections
        if s["depth"] >= 4 and s["record_count"] >= 1 and s["word_count"] >= 50
    ]

    for s in candidates:
        s["_class"] = classify(s)
        s["_score"] = priority_score(s)

    candidates.sort(key=lambda s: s["_score"], reverse=True)

    clean = [s for s in candidates if s["_class"] == "CLEAN"]
    moderate = [s for s in candidates if s["_class"] == "MODERATE"]
    needs_split = [s for s in candidates if s["_class"] == "NEEDS_SPLIT"]

    out: list[str] = []
    out.append(f"# Phase 4.2 — Compile Queue (ranked) — {date.today().isoformat()}")
    out.append("")
    out.append(
        "Generated by `scripts/rank-compile-queue.py` from `parse-book-sections.py --json` output."
    )
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append(f"- Total leaf candidates (depth ≥ 4 ∧ rec ≥ 1 ∧ words ≥ 50): **{len(candidates)}**")
    out.append(f"- CLEAN (100 < words ≤ 500, rec 1–4): **{len(clean)}** → 1 atom each, auto-OK")
    out.append(f"- MODERATE (words 50–100 or 500–1000): **{len(moderate)}** → likely 1 atom, review body")
    out.append(f"- NEEDS_SPLIT (words > 1000 or rec > 5): **{len(needs_split)}** → multiple atoms, manual split required")
    out.append("")
    out.append("### Layer urgency weights (coverage-inverse)")
    out.append("")
    out.append("| Layer | Current coverage | Urgency weight |")
    out.append("|---|---|---|")
    coverage = {1: "34.8%", 2: "29.9%", 3: "6.5%", 4: "10.3%", 5: "14.0%", 6: "15.7%", 7: "9.9%"}
    for layer in sorted(LAYER_URGENCY):
        out.append(f"| L{layer} | {coverage.get(layer, '?')} | {LAYER_URGENCY[layer]:.1f} |")
    out.append("")
    out.append(
        "Priority score = record_count × (1 + depth_bonus) × layer_weight. "
        "depth_bonus = 0.5 for depth ≥ 5."
    )
    out.append("")

    # Classification breakdown by layer
    out.append("### Classification × Layer matrix")
    out.append("")
    out.append("| Layer | CLEAN | MODERATE | NEEDS_SPLIT | Total |")
    out.append("|---|---|---|---|---|")
    for layer in range(1, 8):
        lc = sum(1 for s in clean if s["layer"] == layer)
        lm = sum(1 for s in moderate if s["layer"] == layer)
        ls = sum(1 for s in needs_split if s["layer"] == layer)
        lt = lc + lm + ls
        if lt > 0:
            out.append(f"| L{layer} | {lc} | {lm} | {ls} | {lt} |")
    out.append("")

    # CLEAN queue — the Phase 4.3 first batch source
    out.append("## CLEAN queue — Phase 4.3 first batch candidates")
    out.append("")
    out.append(
        "These sections are sized for 1 atom each. Sorted by priority score (descending). "
        "**Recommended first batch: top 20.**"
    )
    out.append("")
    out.append("| # | § | L | d | words | rec# | score | title |")
    out.append("|---|---|---|---|---|---|---|---|")
    for i, s in enumerate(clean, 1):
        title = s["title"].replace("|", "\\|")
        out.append(
            f"| {i} | {s['section_number']} | L{s['layer']} | {s['depth']} | "
            f"{s['word_count']} | {s['record_count']} | {s['_score']:.1f} | {title} |"
        )
    out.append("")

    # MODERATE queue
    out.append("## MODERATE queue — review before compile")
    out.append("")
    out.append("| # | § | L | d | words | rec# | score | title |")
    out.append("|---|---|---|---|---|---|---|---|")
    for i, s in enumerate(moderate, 1):
        title = s["title"].replace("|", "\\|")
        out.append(
            f"| {i} | {s['section_number']} | L{s['layer']} | {s['depth']} | "
            f"{s['word_count']} | {s['record_count']} | {s['_score']:.1f} | {title} |"
        )
    out.append("")

    # NEEDS_SPLIT queue
    out.append("## NEEDS_SPLIT queue — manual atomization required")
    out.append("")
    out.append(
        "These sections are too large or too record-dense for 1 atom. "
        "Read section body, identify distinct propositions, split into N atoms. "
        "Estimated total atoms from this queue: 2–5× the section count."
    )
    out.append("")
    out.append("| # | § | L | d | words | rec# | score | est. atoms | title |")
    out.append("|---|---|---|---|---|---|---|---|---|")
    for i, s in enumerate(needs_split, 1):
        # Rough atom estimate: 1 per 400 words, minimum 2
        est = max(2, s["word_count"] // 400)
        title = s["title"].replace("|", "\\|")
        out.append(
            f"| {i} | {s['section_number']} | L{s['layer']} | {s['depth']} | "
            f"{s['word_count']} | {s['record_count']} | {s['_score']:.1f} | ~{est} | {title} |"
        )
    out.append("")

    # Batch planning
    total_clean_atoms = len(clean)
    total_split_atoms = sum(max(2, s["word_count"] // 400) for s in needs_split)
    total_moderate_atoms = len(moderate)
    grand_total = total_clean_atoms + total_split_atoms + total_moderate_atoms

    out.append("## Batch planning")
    out.append("")
    out.append(f"- CLEAN: {total_clean_atoms} atoms (1 each)")
    out.append(f"- MODERATE: ~{total_moderate_atoms} atoms (1 each, some may split)")
    out.append(f"- NEEDS_SPLIT: ~{total_split_atoms} atoms (2–10 each)")
    out.append(f"- **Grand total estimate: ~{grand_total} new atoms**")
    out.append(f"- Current atom count: 55")
    out.append(f"- Projected total: ~{55 + grand_total}")
    out.append("")
    out.append("### Recommended batch sequence")
    out.append("")
    out.append("| Batch | Source | Atoms | Method |")
    out.append("|---|---|---|---|")
    out.append(f"| **B1 (validation)** | CLEAN top 20 | 20 | 4 subagents × 5 sections, parallel |")
    out.append(f"| B2 | CLEAN remainder | {max(0, total_clean_atoms - 20)} | same method |")
    out.append(f"| B3 | MODERATE all | ~{total_moderate_atoms} | 1 subagent per section, body review |")
    out.append(f"| B4 | NEEDS_SPLIT all | ~{total_split_atoms} | manual split → subagent per sub-proposition |")
    out.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(out), encoding="utf-8")
    print(f"[ok] wrote {OUTPUT_PATH}")
    print(f"     CLEAN={len(clean)}  MODERATE={len(moderate)}  NEEDS_SPLIT={len(needs_split)}  "
          f"total_candidates={len(candidates)}  est_atoms={grand_total}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
